export const games = [
    {
      id: 1,
      name: "Roblox Premium Edition",
      description: "Join millions of players in an endless world of imagination and creation. Build anything, be anyone!",
      category: "adventure",
      rating: 4.8,
      reviews: 15243,
      releaseDate: "2023-05-15",
      image: "https://images.unsplash.com/photo-1614294148960-9aa740632a87?q=80&w=600",
      popular: true,
      platforms: ["Windows", "Mac", "Mobile"],
      tags: ["Multiplayer", "Building", "Creative"],
      link: "https://your-cpa-content-locker-link.com/roblox"
    },
    {
      id: 2,
      name: "Fortnite Battle Royale",
      description: "The ultimate battle royale experience with building mechanics and seasonal events. Jump into intense battles with friends across the globe!",
      category: "action",
      rating: 4.5,
      reviews: 24876,
      releaseDate: "2023-06-20",
      image: "https://images.unsplash.com/photo-1589241062272-b618104ef4dd?q=80&w=600",
      popular: true,
      platforms: ["Windows", "PlayStation", "Xbox", "Switch", "Mobile"],
      tags: ["Shooter", "Battle Royale", "Multiplayer"],
      link: "https://your-cpa-content-locker-link.com/fortnite"
    },
    {
      id: 3,
      name: "Minecraft Unlimited",
      description: "Create, explore, and survive in a procedurally generated 3D world. Build anything from simple homes to complex machinery!",
      category: "adventure",
      rating: 4.9,
      reviews: 32145,
      releaseDate: "2023-03-10",
      image: "https://images.unsplash.com/photo-1627856014754-2246bc33f36f?q=80&w=600",
      popular: true,
      platforms: ["Windows", "PlayStation", "Xbox", "Switch", "Mobile"],
      tags: ["Sandbox", "Building", "Survival"],
      link: "https://your-cpa-content-locker-link.com/minecraft"
    },
    {
      id: 4,
      name: "Call of Warfare: Modern Combat",
      description: "Experience intense first-person combat in this realistic military shooter. Lead your squad to victory across global battlefields.",
      category: "action",
      rating: 4.7,
      reviews: 18643,
      releaseDate: "2023-08-25",
      image: "https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?q=80&w=600",
      popular: false,
      platforms: ["Windows", "PlayStation", "Xbox"],
      tags: ["FPS", "Military", "Multiplayer"],
      link: "https://your-cpa-content-locker-link.com/call-of-warfare"
    },
    {
      id: 5,
      name: "League of Champions",
      description: "Strategic team-based MOBA with over 150 unique champions. Compete in ranked matches and climb the global leaderboards.",
      category: "strategy",
      rating: 4.6,
      reviews: 21432,
      releaseDate: "2023-04-12",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600",
      popular: true,
      platforms: ["Windows", "Mac"],
      tags: ["MOBA", "Strategy", "Competitive"],
      link: "https://your-cpa-content-locker-link.com/league"
    },
    {
      id: 6,
      name: "Portal Dimensions",
      description: "Mind-bending puzzle game where you manipulate portals to navigate through increasingly complex test chambers.",
      category: "puzzle",
      rating: 4.8,
      reviews: 9876,
      releaseDate: "2023-07-15",
      image: "https://images.unsplash.com/photo-1496096265110-f83ad7f96608?q=80&w=600",
      popular: false,
      platforms: ["Windows", "PlayStation", "Xbox", "Switch"],
      tags: ["Puzzle", "First-person", "Sci-fi"],
      link: "https://your-cpa-content-locker-link.com/portal"
    },
    {
      id: 7,
      name: "Grand Auto Metropolis",
      description: "Open-world action-adventure in a sprawling urban environment. Build your criminal empire through missions and heists.",
      category: "action",
      rating: 4.9,
      reviews: 27542,
      releaseDate: "2023-02-18",
      image: "https://images.unsplash.com/photo-1603670024029-4f02bc5ce54e?q=80&w=600",
      popular: true,
      platforms: ["Windows", "PlayStation", "Xbox"],
      tags: ["Open World", "Action", "Crime"],
      link: "https://your-cpa-content-locker-link.com/grand-auto"
    },
    {
      id: 8,
      name: "Candy Crush Universe",
      description: "The ultimate match-three puzzle experience with thousands of levels and special boosters to collect.",
      category: "puzzle",
      rating: 4.5,
      reviews: 14325,
      releaseDate: "2023-09-05",
      image: "https://images.unsplash.com/photo-1607016284318-d1384f74acd2?q=80&w=600",
      popular: false,
      platforms: ["Mobile", "Web"],
      tags: ["Match-3", "Casual", "Colorful"],
      link: "https://your-cpa-content-locker-link.com/candy-crush"
    },
    {
      id: 9,
      name: "Civilization Nexus",
      description: "Build an empire to stand the test of time. Expand your territory, advance your culture, and lead your people to victory.",
      category: "strategy",
      rating: 4.7,
      reviews: 8764,
      releaseDate: "2023-05-30",
      image: "https://images.unsplash.com/photo-1612404459571-08d4b8995e78?q=80&w=600",
      popular: false,
      platforms: ["Windows", "Mac", "Switch", "Mobile"],
      tags: ["4X", "Turn-based", "Historical"],
      link: "https://your-cpa-content-locker-link.com/civilization"
    },
    {
      id: 10,
      name: "The Elder Scrolls: Legends",
      description: "Epic open-world RPG with a vast continent to explore. Fulfill your destiny as the Dragonborn in this fantasy adventure.",
      category: "adventure",
      rating: 4.8,
      reviews: 19876,
      releaseDate: "2023-11-01",
      image: "https://images.unsplash.com/photo-1563506644863-444710df1e03?q=80&w=600",
      popular: true,
      platforms: ["Windows", "PlayStation", "Xbox", "Switch"],
      tags: ["RPG", "Open World", "Fantasy"],
      link: "https://your-cpa-content-locker-link.com/elder-scrolls"
    },
    {
      id: 11,
      name: "FIFA Ultimate Champions",
      description: "The most realistic soccer simulation with all official teams, players, and stadiums. Compete in online leagues and tournaments.",
      category: "action",
      rating: 4.6,
      reviews: 12543,
      releaseDate: "2023-10-15",
      image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?q=80&w=600",
      popular: true,
      platforms: ["Windows", "PlayStation", "Xbox", "Switch"],
      tags: ["Sports", "Simulation", "Multiplayer"],
      link: "https://your-cpa-content-locker-link.com/fifa"
    },
    {
      id: 12,
      name: "Brain Training Masterclass",
      description: "Sharpen your mind with daily puzzles and challenges designed by neuroscientists to improve cognitive function.",
      category: "puzzle",
      rating: 4.4,
      reviews: 5432,
      releaseDate: "2023-08-12",
      image: "https://images.unsplash.com/photo-1582921017967-79d1cb6702ee?q=80&w=600",
      popular: false,
      platforms: ["Mobile", "Web"],
      tags: ["Educational", "Puzzle", "Brain Training"],
      link: "https://your-cpa-content-locker-link.com/brain-training"
    }
  ];